### ISSUE TITLE
OS X support - no active developer on OS X

### ISSUE THREAD

**Issue by basisbit** [UltraStar-Deluxe/USDX#167]
Currently, none of the active developers of USDX have access to an OS X based system (except for some vm based setup). Thus we can no longer provide support for OS X only problems.
After trying to encourage other friends who are also OS X users to join this project and trying to get some OS X laptop without any success, I will close any OS X related issue report and collect these here as a list.

**Comment by basisbit** [comment]
list of OS X only issue reports:

- [x] [Bug] Webcam is not detected on Mac. #166
- [x] [Bug] Switching from video to visualization to background image back to video does not work properly on MacOS #165
- [x] [MacOS] USB Microphones only produce noise #150
- [x] [OSX] Editor crashes on load #27
- [ ] missing bass_midi output support on OS X

**Comment by bohning** [comment]
Shall I still add issues, which might only be Mac-specific or might concern all OS?

**Comment by basisbit** [comment]
issues which concern all OS should definitely be reported. Regarding OS X only issues, you may post them, then I'll add them to this list.

**Comment by bohning** [comment]
Editor commands not working on Mac:

1. [Ctrl] + Arrow Right/Left: move only beginning of note to earlier/later
On Mac, it switches between desktops (possible solution: use ALT for beginning of note, CMD for end of note, since ALT is left of CMD)

2. =:	increase BPM
The equal sign is produced by SHIFT+0, increasing the GAP by 1000 (0 increases by 10) instead of increasing the BPM

3. [Ctrl] + C/V:	copy/paste current sentence
Works as expected. However, on Mac copy is usually on CMD+C and paste is on CMD+V. Using CTRL is counterintuitive.

4. [Shift] + P:	play current sentence midi
Does not play anything on Mac.

5. [Ctrl] + [Shift] + P:	play current sentence audio and midi
Behaves as if only P was pressed (audio + clicks, no midi).

6. [Shift] + M:	multiply BPM by 2 but keep correct timings
Works as expected, only displays: INFO_MULTIPLIED (display string seems to be missing)

7. [Ctrl] + [Del]	delete current note
Does not delete anything.

8. [+ on numberpad]	Increase tone of all notes by 1
[- on numberpad]	Decrease tone of all notes by 1
[Shift] + [+ on numberpad]	Increase tone of all notes by octave
[Shift] + [- on numberpad]	Decrease tone of all notes by octave
What to do without numberpad? There is no number pad on the internal Mac keyboard (and presumably many Windows notebook keyboards).

9. 4	copy 4 sentence, 5 copy 5 sentence
I don't really understand this. Simply hitting 4 will copy the current and the following 3 sentences, which can then be pasted by CTRL+V? If so, this doesn't work (on Mac at least, that is).

**Comment by AlexanderS** [comment]
I might have access to a Mac Book Pro. But I am having no experience in developing on macOS.

**Comment by bohning** [comment]
@AlexanderS I'd be happy to support, but I have no experience in either programming Pascal nor programming on MacOS. I am able to compile USDX on the command line, but I am having trouble to get the Lazarus environment to compile the code. What I get is:

Projekt:Ausführen des Befehls vor: Exit code 512, Fehler: 17
Panic: ===================================
Panic: Changed files:
Panic: config-darwin.inc
Panic: ===================================
Panic: -----------------------------------
Panic: Clean old object data...
Panic: /Applications/Xcode.app/Contents/Developer/usr/bin/make clean_obj
Panic: rm -f "../game/ultrastardx"
Panic: rm -f -r "../build/fpc-i386-darwin"
Panic: -----------------------------------
Panic: ../dists/autogen/install-sh -c -d "../build/fpc-i386-darwin"
Panic: /Applications/Xcode.app/Contents/Developer/usr/bin/make create-pathinfo
Panic: /bin/sh: fpc: command not found
Panic: make: *** [../game/ultrastardx] Error 127
Panic: echo "INSTALL_DATADIR = '/usr/local/share/ultrastardx';" > paths.inc
Panic: fpc -Px86_64 -k"-macosx_version_min 10.4 -undefined dynamic_lookup -headerpad_max_install_names -L/usr/X11/lib -L/usr/local/Cellar/ffmpeg/2.8.6/lib -L/usr/local/Cellar/freetype/2.6.3/lib -L/usr/local/Cellar/libpng/1.6.21/lib -L/usr/local/Cellar/lua/5.2.4_3/lib -L/usr/local/Cellar/pcre/8.38/lib -L/usr/local/Cellar/portaudio/19.20140130/lib -L/usr/local/lib" -Fi../src/lib/JEDI-SDL/SDL/Pas -Fu. -FU../build/fpc-i386-darwin -o../game/ultrastardx ultrastardx.dpr
Panic: tool stopped with exit code 512. Use context menu to get more information.

It seems that fpc is not found, but it was correctly (?) auto-detected by the IDE (otherwise it wouldn't start).

**Comment by bohning** [comment]
Where would I find the error.log on Mac? I looked for it in `/Users/markus/Library/Application Support` where I find the `config.ini` and the `cover.db` with today's date (having launched USDX), but no error.log. Any ideas? @kamischi @AlexanderS @rhaamo?

**Comment by kamischi** [comment]
In "~/Library/Logs/ Ultrastar Deluxe/Error.log". This is according to the guidelines from Apple.

**Comment by bohning** [comment]
Thanks for the quick feedback!

**Comment by bohning** [comment]
It would be helpful if hidden backup files (what are these exactly anyways) starting with `._` would be ignored. Currently, they are analyzed and leave tracks in the `error.log` such as

`ERROR:  File contains empty lines or BPM tag missing: /Volumes/Karaoke/Kettcar - Deiche [VIDEO] [SC]/._Kettcar - Deiche.txt
ERROR:  AnalyseFile failed for "/Volumes/Karaoke/Kettcar - Deiche [VIDEO] [SC]/._Kettcar - Deiche.txt".`

**Comment by kamischi** [comment]
These files are not hidden backup files but mirror files, where properties of the files are kept on file systems less capable than HFS, such as FAT or NTFS. Examples are the position and settings of folder or file views of the Finder, editor positions of text editors and so on. They can be safely neglected or put to ignore lists. If they are not present, the default setting for such properties is taken.

**Comment by ePirat** [comment]
I will reopen and tag macOS specific issues with the macOS label, so those can be easily searched and filtered.

I'll try to fix most of them.

**Comment by dgruss** [comment]
most if not all of the issues should be resolved now?

**Comment by barbeque-squared** [comment]
Yeah I'll close this. The development as a whole has also changed a lot over the years -- having CI that builds Mac is a godsend for starters. It's also much more likely that new features that don't work on all platforms will just get outright rejected these days.
